<?php

/**
 * Implements hook_feeds_plugins().
 */
function feeds_jsonpath_parser_feeds_plugins() {
  $path = drupal_get_path('module', 'feeds_jsonpath_parser');
  $info = array();
  $info['FeedsJSONPathParser'] = array(
    'name'        => t('JSONPath parser'),
    'description' => t('Parse JSON using JSONPath.'),
    'handler' => array(
      'parent' => 'FeedsParser',
      'class'  => 'FeedsJSONPathParser',
      'file'   => 'FeedsJSONPathParser.inc',
      'path'   => $path,
    ),
  );
  return $info;
}

/**
 * Implements hook_enable().
 *
 * Clear Feed's plugin cache so that this plugin shows up.
 */
function feeds_jsonpath_parser_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Returns the path of the JSONPath library.
 *
 * @return string|bool
 *   The relative path of the JSONPath directory, or false if not found.
 */
function feeds_jsonpath_parser_library_path() {
  $search = glob(dirname(__FILE__) . '/jsonpath*.php');

  if ($file = reset($search)) {
    $path = dirname($file);
  }
  elseif (module_exists('libraries') && file_exists(libraries_get_path('jsonpath'))) {
    $path = libraries_get_path('jsonpath');
  }
  elseif (file_exists(DRUPAL_ROOT . '/sites/all/libraries/jsonpath')) {
    $path = 'sites/all/libraries/jsonpath';
  }
  // This is defined when simpletest downloads the library for us.
  elseif (defined('FEEDS_JSONPATH_LIBRARY_PATH')) {
    $path = FEEDS_JSONPATH_LIBRARY_PATH . '/jsonpath';
  }

  if (!isset($path)) {
    return FALSE;
  }

  // Newer forks of JSONPath are all modern and fancy with their autoloaders.
  if (file_exists($path . '/vendor/autoload.php')) {
    return $path . '/vendor/autoload.php';
  }
  // Old school. Look for multiple versions.
  foreach (glob($path . '/jsonpath*.php') as $file) {
    return $file;
  }

  return FALSE;
}
