<?php
/**
 * @file
 * Parse a JSON document using JSONPath.
 */

/**
 * Implements hook_autoload_info().
 */
function feeds_jsonpath_parser_autoload_info() {
  return array(
    'FeedsJSONPathParser' => 'FeedsJSONPathParser.inc',
  );
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_jsonpath_parser_feeds_plugins() {
  return array(
    'FeedsJSONPathParser' => array(
      'name' => t('JSONPath parser'),
      'description' => t('Parse JSON files using JSONPath.'),
      'handler' => array(
        'parent' => 'FeedsParser',
        'class' => 'FeedsJSONPathParser',
        'file' => 'FeedsJSONPathParser.inc',
        'path' => backdrop_get_path('module', 'feeds_jsonpath_parser'),
      ),
    ),
  );
}

